import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import { Nunito } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/navbar';
import { SessionProvider } from 'next-auth/react';
// import RegisterModal from '@/components/modals/register-modal';
import ToasterProvider from '@/providers/toaster-provider';
// import LoginModal from '@/components/modals/login-modal';
import { auth } from '@/auth';
import getCurrentUser from '@/actions/get-current-user';
import AuthModal from '@/components/modals/auth-modal';
import RentModal from '@/components/modals/rent-modal';
import SearchModal from '@/components/modals/search-modal';

// import ClientOnly from '@/lib/client-only';

const inter = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const currentUser = await getCurrentUser();
  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <body className={inter.className}>
          {/* <ClientOnly> */}
          <ToasterProvider />
          <SearchModal />
          <RentModal />
          {/* <LoginModal />
          <RegisterModal /> */}
          <AuthModal />
          <Navbar currentUser={currentUser} />
          {/* </ClientOnly> */}
          <div className='pb-20 pt-28'>{children}</div>
        </body>
      </html>
    </SessionProvider>
  );
}
